---
title: "Final Viz"
author: "Alan Wang"
date: "2023-07-15"
output: pdf_document
---

```{r}
library(nparLD)
library(coin)
library(PMCMRplus)
library(cowplot)
library(dplyr)
library(patchwork)
library(lme4)
library(lmerTest)
library(emmeans)
library(multcomp)
library(nlme)
library(e1071)
library(psych)
library(merTools)
library(glmmTMB)
library(modelr)
library(brms)
require(MASS)
library(glmmTMB)
library(ggplot2)
library(reshape2)
library(tidyverse)
```

```{r}
med <- rdata %>%
  group_by(PepConc, DayC3) %>%
  summarise(medians = median(intst3))

med1 <- rdata %>%
  group_by(Peptide, DayC3) %>%
  summarise(medians1 = median(intst3))

bp <- ggplot() +
  geom_boxplot(data = rdata, aes(x = DayC3, y = intst3, fill = PepConc), position = position_dodge(width = 0.8), width = 0.6) +
  labs(x = "Time", y = "Internalized NP Proportion", title = "Internalized NP Proportion Across Peptide Concentration and Time") +
  scale_fill_discrete(name = "Peptide Conc") +
  facet_grid(PepConc ~ ., scales = "free_x", space = "free_x") +
  geom_line(data = med, aes(x = DayC3, y = medians, group = PepConc), linetype = "dashed",col   = 'red', size = 0.5, inherit.aes = FALSE)
  
bp

bp1 <- ggplot() +
  geom_boxplot(data = rdata, aes(x = DayC3, y = intst3, fill = Peptide), position = position_dodge(width = 0.8), width = 0.6) +
  labs(x = "Time", y = "Internalized NP Proportion", title = "Internalized NP Proportion Across Peptide Type and Time") +
  scale_fill_discrete(name = "Peptide Type") +
  facet_grid(Peptide ~ ., scales = "free_x", space = "free_x") +
  geom_line(data = med1, aes(x = DayC3, y = medians1, group = Peptide), linetype = "dashed",col   = 'red', size = 0.5, inherit.aes = FALSE)

bp1

combined_plots <- plot_grid(bp1, bp, nrow = 2)
print(combined_plots) 
 
```

```{r}
# BINDING VIZ + COMBINED
# there wre some intst3y variables way above 1
rdata <- rdata %>% 
  mutate(intst3y = ifelse(intst3y > 1, 0.999, intst3y))

med2 <- rdata %>%
  group_by(PepConc, DayC3) %>%
  summarise(medians2 = median(intst3y))

med3 <- rdata %>%
  group_by(Peptide, DayC3) %>%
  summarise(medians3 = median(intst3y))

bp2 <- ggplot(rdata, aes(x = DayC3, y = intst3y, fill = PepConc)) +
  geom_boxplot(position = position_dodge(width = 0.8), width = 0.6) +
  labs(x = "Time", y = "Cell-Bound NP Proportion", title = "Cell-Bound NP Proportion Across Peptide Concentration and Time") +
  scale_fill_discrete(name = "Peptide Conc") +
  facet_grid(PepConc ~ ., scales = "free_y", space = "free_y") +
  geom_line(data = med2, aes(x = DayC3, y = medians2, group = PepConc), linetype = "dashed",col = 'red', size = 0.5, inherit.aes = FALSE)

bp3 <- ggplot() +
  geom_boxplot(data = rdata, aes(x = DayC3, y = intst3y, fill = Peptide), position = position_dodge(width = 0.8), width = 0.6) +
  labs(x = "Time", y = "Cell-Bound NP Proportion", title = "Cell-Bound NP Proportion Across Peptide Type and Time") +
  scale_fill_discrete(name = "Peptide Type") +
  facet_grid(Peptide ~ ., scales = "free_x", space = "free_x") +
  geom_line(data = med3, aes(x = DayC3, y = medians3, group = Peptide), linetype = "dashed",col   = 'red', size = 0.5, inherit.aes = FALSE)



combined_plots <- plot_grid(bp3, bp2, nrow = 2)
print(combined_plots)


count_result <- rdata %>%
  group_by(CE) %>%
  summarise(count = n())

# Print the result
print(count_result)

```

```{r}
# LOCATION EFFECT
l <- ggplot(data = rdata, aes(x = CE, y = intst3)) +
  geom_boxplot() +
  labs(x = "Location (center, center edge, edge, edge center)", y = "Internalized NP Proportion")

l +
  stat_summary(fun = median, geom = "line", linetype = "dashed", aes(group = 1), col = 'red')

```
```{r}
# For the 'time' factor
time_test <- with(rdata, kruskal_test(intst3 ~ DayC3, strata = block))
print(time_test)

# For the 'peptide' factor
peptide_test <- with(rdata, kruskal_test(intst3 ~ PepConc, strata = block))
print(peptide_test)

# For the 'location' factor
location_test <- with(rdata, kruskal_test(intst3 ~ location, strata = block))
print(location_test)

# List of factors
factors <- c("DayC3", "PepConc", "location")

r1data$blocked <- factor(r1data$Mouse)
conc <- with(r1data, kruskal_test(intst3 ~ Conc, strata = blocked))
print(conc)
```
```{r}
med1 <- rdata %>%
  group_by(PepConc, DayC3) %>%
  summarise(medians1 = median(intst3y))

bp1 <- ggplot(rdata, aes(x = DayC3, y = intst3y, fill = PepConc)) +
  geom_boxplot(position = position_dodge(width = 0.8), width = 0.6) +
  labs(x = "Time", y = "Cell-Bound NP Proportion", title = "Cell-Bound NP Proportion Across Peptide Concentration and Time") +
  scale_fill_discrete(name = "Peptide Concentration") +
  facet_grid(PepConc ~ ., scales = "free_y", space = "free_y") +
  geom_line(data = med1, aes(x = DayC3, y = medians1, group = PepConc), linetype = "dashed",col = 'red', size = 0.5, inherit.aes = FALSE)
bp1

combined_plots <- plot_grid(bp1, bp, nrow = 2)
print(combined_plots)
```

```{r}
avg_days <- rdata %>%
  group_by(DayC3) %>%
  summarize(avg_day = mean(Day))

avg_days

med1
med
med2
med3

slope_radint <- c((.24-.6210)/(5.635762-1.828947), (.001-.2400)/(11.516129-5.635762), (.0010-0.6210)/(11.516129-1.828947))
slope_rgdint <- c((0.762-0.987)/(5.635762-1.828947), (0.083-0.762)/(11.516129-5.635762), (0.083-0.762)/(11.516129-1.828947))
slope_rgd150y



slope_rady <- c((0.0760-0.1570)/(5.635762-1.828947), (0.0000-0.0760)/(11.516129-5.635762), (0.0000-0.1570)/(11.516129-1.828947))
slope_rgdy <- c((0.1105-0.1510)/(5.635762-1.828947), (0.0300-0.1105	)/(11.516129-5.635762), (0.0300-0.1510)/(11.516129-1.828947))

slope_rgd150int <- c((0.6635-0.9840)/(5.635762-1.828947), (0.0590-0.6635)/(11.516129-5.635762), (0.0590-0.9840)/(11.516129-1.828947))
slope_rgd400int <- c((0.8565-0.9885)/(5.635762-1.828947), (0.7520-0.8565	)/(11.516129-5.635762), (0.7520-0.9885)/(11.516129-1.828947))

slope_rgd150y <- c((0.073-0.110)/(5.635762-1.828947), (0.023-0.073)/(11.516129-5.635762), (0.023-0.110)/(11.516129-1.828947))
slope_rgd400y <- c((0.249-0.220)/(5.635762-1.828947), (0.162-0.249)/(11.516129-5.635762), (0.162-0.220)/(11.516129-1.828947))

```





